const SLRAction = {
	0: {"inicio": 'S2',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	1: {"inicio": '',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": 'Acc'},
	2: {"inicio": '',       "varinicio": 'S4', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	3: {"inicio": '',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'S10',     "escreva": 'S11',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S12',       "atr": '',      "opa": '',      "se": 'S14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": 'S9',      "S": ''},
	4: {"inicio": '',       "varinicio": '', "varfim": 'S53',  "inteiro": 'S48',
		"real": 'S49',     "literal": 'S50',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	5: {"inicio": '',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": 'R2'},
	6: {"inicio": '',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'S10',     "escreva": 'S11',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S12',       "atr": '',      "opa": '',      "se": 'S14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": 'S9',      "S": ''},
	7: {"inicio": '',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'S10',     "escreva": 'S11',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S12',       "atr": '',      "opa": '',      "se": 'S14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": 'S9',      "S": ''},
	8: {"inicio": '',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'S10',     "escreva": 'S11',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S12',       "atr": '',      "opa": '',      "se": 'S14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": 'S9',      "S": ''},
	9: {"inicio": '',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": 'R32'},
	10: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S17',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	11: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": 'S21',      "num": 'S22',
		"id": 'S23',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	12: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": 'S24',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	13: {"inicio": '',       "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'S10',     "escreva": 'S11',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S12',       "atr": '',      "opa": '',      "se": 'S14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'S44',    "fim": '',      "S": ''},
	14: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": 'S32',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	15: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": 'R12'},
	16: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": 'R18'},
	17: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'S18',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	18: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R13',     "escreva": 'R13',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R13',       "atr": '',      "opa": '',      "se": 'R13',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R13',    "fim": 'R13',      "S": ''},
	19: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'S20',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	20: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R14',     "escreva": 'R14',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R14',       "atr": '',      "opa": '',      "se": 'R14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R14',    "fim": 'R14',      "S": ''},
	21: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'R15',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	22: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'R16',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	23: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'R17',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	24: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": 'S31',
		"id": 'S30',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	25: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'S26',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	26: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R19',     "escreva": 'R19',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R19',       "atr": '',      "opa": '',      "se": 'R19',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R19',    "fim": 'R19',      "S": ''},
	27: {"inicio": '',      "varinicio": '', "varfim": 'R21',  "inteiro": 'R21',
		"real": 'R21',     "literal": 'R21',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": 'S28',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	28: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": 'S31',
		"id": 'S30',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	29: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'R20',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	30: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'R22',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": 'R22',      "se": '',
		"ab_p": '',     "fc_p": 'R22',     "entao": '',    "opr": 'R22',
		"fimse": '',    "fim": '',      "S": ''},
	31: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'R23',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": 'R23',      "se": '',
		"ab_p": '',     "fc_p": 'R23',     "entao": '',    "opr": 'R23',
		"fimse": '',    "fim": '',      "S": ''},
	32: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": 'S31',
		"id": 'S30',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	33: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": 'S34',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	34: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": 'S35',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	35: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R26',     "escreva": 'R26',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R26',       "atr": '',      "opa": '',      "se": 'R26',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R26',    "fim": '',      "S": ''},
	36: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": 'S37',
		"fimse": '',    "fim": '',      "S": ''},
	37: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": 'S31',
		"id": 'S30',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	38: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": 'R27',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	39: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R25',     "escreva": 'R25',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R25',       "atr": '',      "opa": '',      "se": 'R25',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R25',    "fim": 'R25',      "S": ''},
	40: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'S10',     "escreva": 'S11',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S12',       "atr": '',      "opa": '',      "se": 'S14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'S44',    "fim": '',      "S": ''},
	41: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'S10',     "escreva": 'S11',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S12',       "atr": '',      "opa": '',      "se": 'S14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'S44',    "fim": '',      "S": ''},
	42: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'S10',     "escreva": 'S11',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S12',       "atr": '',      "opa": '',      "se": 'S14',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'S44',    "fim": '',      "S": ''},
	43: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R28',     "escreva": 'R28',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R28',       "atr": '',      "opa": '',      "se": 'R28',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R28',    "fim": 'R28',      "S": ''},
	44: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R31',     "escreva": 'R31',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R31',       "atr": '',      "opa": '',      "se": 'R31',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R31',    "fim": 'R31',      "S": ''},
	45: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R29',     "escreva": 'R29',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R29',       "atr": '',      "opa": '',      "se": 'R29',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R29',    "fim": 'R29',      "S": ''},
	46: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R30',     "escreva": 'R30',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R30',       "atr": '',      "opa": '',      "se": 'R30',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": 'R30',    "fim": 'R30',      "S": ''},
	47: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R3',     "escreva": 'R3',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R3',       "atr": '',      "opa": '',      "se": 'R3',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": 'R3',      "S": ''},
	48: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R9',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	49: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R10',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	50: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R11',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	51: {"inicio": '',	"varinicio": '', "varfim": 'S53',  "inteiro": 'S48',
		"real": 'S49',     "literal": 'S50',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	52: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R4',     "escreva": 'R4',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R4',       "atr": '',      "opa": '',      "se": 'R4',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": 'R4',      "S": ''},
	53: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'S54',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	54: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": 'R5',     "escreva": 'R5',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'R5',       "atr": '',      "opa": '',      "se": 'R5',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": 'R5',      "S": ''},
	55: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S58',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	56: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'S57',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	57: {"inicio": '',      "varinicio": '', "varfim": 'R6',  "inteiro": 'R6',
		"real": 'R6',     "literal": 'R6',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	58: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'R8',     "vir": 'S59',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	59: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": 'S58',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	60: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": 'R7',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": ''},
	61: {"inicio": '',      "varinicio": '', "varfim": '',  "inteiro": '',
		"real": '',     "literal": '',  "leia": '',     "escreva": '',
		"pt_v": '',     "vir": '',      "lit": '',      "num": '',
		"id": '',       "atr": '',      "opa": '',      "se": '',
		"ab_p": '',     "fc_p": '',     "entao": '',    "opr": '',
		"fimse": '',    "fim": '',      "S": 'R24'}
}


module.exports = {
	SLRAction
}